version: '3.8'
services:
  db:
    image: postgres:15.19@sha256:dfbbb0ad8cab91d41e99123664e37a9b25d0413426d4fb3154e4d668e5d35246
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: library/redis:7.0-bridge
