version: '3.8'
services:
  db:
    image: postgres:15.19@sha256:c961aa287d8698297cb26cdfadfbe9fd2cbaf77e53cfffe9636e8d8a1e4d842c
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: library/redis:7.0-bridge
